services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_backup:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
    container_name: site
    command: ./start.sh 
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./db_backup:/app/db_backup
    env_file:
      - .env
    expose:
      - "8000"
    environment:
      - PGPASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data: