# Generated by Django 4.1 on 2024-02-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pastor', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='foto_pastor/%Y/%m/%d')),
                ('publicado', models.BooleanField(default=True)),
            ],
        ),
    ]
