# Generated by Django 4.1 on 2024-02-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastores',
            name='posicao',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
