# Generated by Django 4.1 on 2024-02-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0003_ministerios_alter_pastores_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrosel_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_imagem', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='carrosel')),
                ('link_pagina', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
