# Generated by Django 4.1 on 2024-02-15 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0005_carrosel_index_posicao_carrosel_index_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('data_evento', models.DateField(default=datetime.datetime(2024, 2, 15, 16, 29, 36, 351225))),
                ('hora_evento', models.TimeField(verbose_name=datetime.datetime(2024, 2, 15, 16, 29, 36, 351224))),
                ('descricao_evento', models.CharField(max_length=2000)),
                ('banner_evento', models.ImageField(upload_to='eventos/banners')),
                ('foto_card_evento', models.ImageField(upload_to='eventos/card_evento')),
            ],
        ),
    ]
