# Generated by Django 4.1 on 2024-02-15 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0006_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='data_evento',
            field=models.DateField(default=datetime.datetime(2024, 2, 15, 16, 58, 53, 682023)),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='hora_evento',
            field=models.TimeField(null=True),
        ),
    ]
