# Generated by Django 4.1 on 2024-02-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0007_alter_eventos_data_evento_alter_eventos_hora_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='data_evento',
            field=models.DateField(null=True),
        ),
    ]
