# Generated by Django 4.1 on 2024-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0010_alter_eventos_descricao_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerios',
            name='card_ministerio',
            field=models.ImageField(default='', upload_to='ministerios/card_index'),
        ),
    ]
