# Generated by Django 4.1 on 2024-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0011_ministerios_card_ministerio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministerios',
            name='card_ministerio',
            field=models.ImageField(upload_to='ministerios/card_index'),
        ),
    ]
