# Generated by Django 4.1 on 2024-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0013_ministerios_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lideres_Ministerios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lider', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto_lider', models.ImageField(upload_to='ministerios/lider_ministerio')),
            ],
        ),
    ]
