# Generated by Django 4.1 on 2024-02-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0014_lideres_ministerios'),
    ]

    operations = [
        migrations.AddField(
            model_name='lideres_ministerios',
            name='ministerio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='site_obpc.ministerios'),
        ),
    ]
