# Generated by Django 4.1 on 2024-02-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0015_lideres_ministerios_ministerio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lideres_ministerios',
            name='posicao',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
