# Generated by Django 4.1 on 2024-02-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0016_lideres_ministerios_posicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='Endereco_evento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
