# Generated by Django 4.1 on 2024-02-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0017_eventos_endereco_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerios',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ministerios',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
