# Generated by Django 4.1 on 2024-02-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0018_ministerios_email_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_obpc.ministerios'),
        ),
    ]
