# Generated by Django 4.1 on 2024-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0019_eventos_ministerio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerios',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ministerios',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
