# Generated by Django 4.1 on 2024-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0021_congregacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacoes',
            name='foto_banner',
            field=models.ImageField(help_text='Dimensão: 1415 x 480 px', upload_to='congregacoes/banner'),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='foto_dirigentes',
            field=models.ImageField(help_text='Dimensão: 400 x 480 px', upload_to='congregacoes/digirentes'),
        ),
    ]
