# Generated by Django 4.1 on 2024-03-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0022_alter_congregacoes_foto_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso_extenso', models.CharField(max_length=100)),
                ('nome_curso_abreviado', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=5000, null=True)),
                ('duracao', models.CharField(max_length=100)),
                ('descricao_duracao', models.CharField(blank=True, max_length=2000, null=True)),
                ('periodo', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('modalidade', models.CharField(max_length=100)),
                ('investimento', models.CharField(max_length=100)),
                ('descricao_investimento', models.CharField(blank=True, max_length=2000, null=True)),
                ('informacoes_complementares', models.CharField(blank=True, max_length=5000, null=True)),
                ('nome_coordenacao', models.CharField(blank=True, max_length=2000, null=True)),
                ('foto_coordenacao', models.ImageField(help_text='Dimensão: 112 x 112 px', upload_to='cursos/coordenador')),
                ('foto_banner', models.ImageField(help_text='Dimensão: 330 x 260 px', upload_to='cursos/banner')),
                ('link_inscricao', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
