# Generated by Django 4.1 on 2024-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0023_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_devocional', models.CharField(max_length=100)),
                ('texto_devocional', models.CharField(blank=True, max_length=10000, null=True)),
                ('autor', models.CharField(max_length=100)),
                ('banner_home', models.ImageField(help_text='Dimensão: 1519 x 510 px', upload_to='devocional/banner')),
                ('banner_pagina_devocional', models.ImageField(help_text='Dimensão: 330 x 260 px', upload_to='devocional/banner')),
                ('data_devocional', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pastores',
            name='foto',
            field=models.ImageField(help_text='Dimensão: 1051 x 1247 px', upload_to='pastores/foto_pastor'),
        ),
    ]
