# Generated by Django 4.1 on 2024-07-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0024_devocional_alter_pastores_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carrosel_index',
            name='imagem',
            field=models.ImageField(help_text='Dimensão: 1216 x 606 px', upload_to='carrosel'),
        ),
        migrations.AlterField(
            model_name='devocional',
            name='banner_pagina_devocional',
            field=models.ImageField(help_text='Dimensão: 800 x 530 px', upload_to='devocional/banner'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='banner_evento',
            field=models.ImageField(help_text='Dimensão: 800 x 480 px', upload_to='eventos/banners'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='foto_card_evento',
            field=models.ImageField(help_text='Dimensão: 248 x 224 px', upload_to='eventos/card_evento'),
        ),
        migrations.AlterField(
            model_name='lideres_ministerios',
            name='foto_lider',
            field=models.ImageField(help_text='Dimensão: 176 x 99 px', upload_to='ministerios/lider_ministerio'),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='card_ministerio',
            field=models.ImageField(help_text='Dimensão: 320 x 320 px', upload_to='ministerios/card_index'),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='foto_ministerio',
            field=models.ImageField(help_text='Dimensão: 496 x 388 px', upload_to='ministerios/foto_ministerios'),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='logo_ministerio',
            field=models.ImageField(help_text='Dimensão: 165 x 48 px', upload_to='ministerios/logo_ministerio'),
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('foto', models.ImageField(help_text='Dimensão: 380 x 200 px', upload_to='servicos/foto_empresas')),
                ('facebook_empresa', models.CharField(max_length=100)),
                ('instagram_empresa', models.CharField(max_length=100)),
                ('whatsapp_empresa', models.CharField(max_length=100)),
                ('site_empresa', models.CharField(max_length=100)),
                ('publicado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='site_obpc.categoria_servicos')),
            ],
        ),
    ]
