# Generated by Django 4.1 on 2024-07-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0025_categoria_servicos_alter_carrosel_index_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='facebook_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='instagram_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='site_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='whatsapp_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
