# Generated by Django 4.1 on 2024-08-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0026_alter_servicos_facebook_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=5000)),
                ('data_publicacao', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventos',
            name='foto_card_evento',
            field=models.ImageField(help_text='Dimensão: 400 x 400 px', upload_to='eventos/card_evento'),
        ),
        migrations.AlterField(
            model_name='lideres_ministerios',
            name='foto_lider',
            field=models.ImageField(help_text='Dimensão: 300 x 250 px', upload_to='ministerios/lider_ministerio'),
        ),
    ]
