# Generated by Django 4.1 on 2024-08-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0027_quemsomos_alter_eventos_foto_card_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemsomos',
            name='texto',
            field=models.CharField(max_length=7000),
        ),
    ]
