# Generated by Django 4.1 on 2024-08-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0028_alter_quemsomos_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='quemsomos',
            name='nome_qsomos',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
