# Generated by Django 4.1 on 2024-08-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0029_quemsomos_nome_qsomos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='data_evento',
            new_name='data_fim',
        ),
        migrations.AddField(
            model_name='eventos',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='banner_evento',
            field=models.ImageField(help_text='Dimensão: 600 x 600 px', upload_to='eventos/banners'),
        ),
    ]
