# Generated by Django 4.1 on 2024-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0030_rename_data_evento_eventos_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
