# Generated by Django 4.1 on 2024-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0031_alter_eventos_data_fim_alter_eventos_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregacoes',
            name='descricao_congregacao',
        ),
        migrations.AddField(
            model_name='congregacoes',
            name='diritente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
