# Generated by Django 4.1 on 2024-09-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0032_remove_congregacoes_descricao_congregacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congregacoes',
            old_name='diritente',
            new_name='dirigente',
        ),
    ]
