# Generated by Django 4.1 on 2024-09-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0033_rename_diritente_congregacoes_dirigente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacoes',
            name='foto_banner',
            field=models.ImageField(blank=True, help_text='Dimensão: 1415 x 480 px', null=True, upload_to='congregacoes/banner'),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='foto_dirigentes',
            field=models.ImageField(blank=True, help_text='Dimensão: 400 x 480 px', null=True, upload_to='congregacoes/digirentes'),
        ),
    ]
