# Generated by Django 4.1 on 2024-09-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0036_instagramapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramapi',
            name='permalink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
