# Generated by Django 4.1 on 2024-10-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0040_youtubeapi_alter_ministerios_logo_ministerio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
