# Generated by Django 5.1.4 on 2025-01-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0042_alter_carrosel_index_link_pagina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descricao_duracao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nome_coordenacao',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao_evento',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='descricao_ministerio',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pastores',
            name='biografia',
            field=models.TextField(max_length=100),
        ),
    ]
