# Generated by Django 5.1.4 on 2025-01-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0043_alter_cursos_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='descricao',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descricao_investimento',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='informacoes_complementares',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
