# Generated by Django 5.1.4 on 2025-01-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0045_alter_cursos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosel_index',
            name='link_pagina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrosel_index',
            name='nome_imagem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria_servicos',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='cultos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='dirigente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='link_maps',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='congregacoes',
            name='nome_congregacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descricao',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descricao_duracao',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descricao_investimento',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='duracao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='informacoes_complementares',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='investimento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='link_inscricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='local',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='modalidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nome_coordenacao',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nome_curso_abreviado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nome_curso_extenso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='periodo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devocional',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devocional',
            name='texto_devocional',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='devocional',
            name='titulo_devocional',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='Endereco_evento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao_evento',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nome_evento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instagramapi',
            name='caption',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='instagramapi',
            name='children',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instagramapi',
            name='id_instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instagramapi',
            name='media_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instagramapi',
            name='media_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instagramapi',
            name='permalink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instagramapi',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instagramapi',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instagramtoken',
            name='token',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lideres_ministerios',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lideres_ministerios',
            name='nome_lider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='descricao_ministerio',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='nome_ministerio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ministerios',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pastores',
            name='biografia',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='pastores',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pastores',
            name='nome_pastor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='nome_qsomos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='texto',
            field=models.CharField(max_length=7000),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='facebook_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='instagram_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='nome_empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='site_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='whatsapp_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeapi',
            name='liveBroadcastContent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeapi',
            name='publishedAt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeapi',
            name='thumbnails',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeapi',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeapi',
            name='videoId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
