# Generated by Django 5.1.4 on 2025-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_obpc', '0046_alter_carrosel_index_link_pagina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastores',
            name='biografia',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
